name: Security Analysis

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Exécution hebdomadaire le dimanche à minuit
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - name: Check outdated dependencies
      run: npm outdated
      continue-on-error: true
